#pragma once

#define MAX_MALLOC_RETRIES 1000000

#define MINIMUM_CLOUDFLARE_API_KEY_LENGTH 16
#define MAXIMUM_CLOUDFLARE_API_KEY_LENGTH 64

#define MINIMUM_URL_LENGTH 3
#define MAXIMUM_URL_LENGTH 253

#define DEFAULT_MINUTES_BETWEEN_UPDATES 15
#define DEFAULT_PROPAGATION_DELAY_SECONDS 60

#define CLOUDFLARE_API_KEY_ENV_VAR "CLOUDFLARE_API_KEY"
#define DOMAINS_ENV_VAR "DOMAINS"
#define PROXIED_ENV_VAR "PROXIED"
#define MINUTES_BETWEEN_UPDATES_ENV_VAR "MINUTES_BETWEEN_UPDATES"
#define PROPAGATION_DELAY_SECONDS_ENV_VAR "PROPAGATION_DELAY_SECONDS"
#define IP_V4_APIS_ENV_VAR "IP_V4_APIS"

#define DOMAIN_DELIMITER ","

