#pragma once

#define MAX_MALLOC_RETRIES 1000000

#define MINIMUM_CLOUDFLARE_API_KEY_LENGTH 16
#define MAXIMUM_CLOUDFLARE_API_KEY_LENGTH 64

#define MINIMUM_URL_LENGTH 3
#define MAXIMUM_URL_LENGTH 253

#define DEFAULT_MINUTES_BETWEEN_UPDATES 15
#define DEFAULT_PROPAGATION_DELAY_SECONDS 60


